export const siteContent = {
  cs: {
    navigation: [
      { label: "Trénink", href: "#coaching" },
      { label: "Proces", href: "#process" },
      { label: "O mně", href: "#about" },
      { label: "Reference", href: "#results" },
      { label: "Kontakt", href: "#contact" },
    ],
    header: {
      homeLabel: "Matej Červenka — domů",
      navigationLabel: "Hlavní navigace",
      languageLabel: "Jazyk obsahu",
    },
    hero: {
      ariaLabel: "Tréninkový manifest",
      progressLabel: "Postup kapitol",
      chapters: [
        { discipline: "Síla", headline: ["Buduj", "sílu."] },
        { discipline: "Vytrvalost", headline: ["Buduj", "vytrvalost."] },
        { discipline: "Výkon", headline: ["Buduj", "výkon."] },
      ],
      finalLabel: "OSOBNÍ TRENÉR · ZLÍN",
      finalLineOne: "Vybuduj tělo,",
      finalLineTwo: "které zvládne",
      finalLineThree: "víc.",
      finalLead: "Získej sílu, lepší postavu a kondici díky tréninku nastavenému podle tvého cíle a aktuální úrovně.",
      finalServices: "1:1 · DUO / MALÁ SKUPINA · KONDIČNÍ BOX",
      finalCta: "Chci začít",
      skipCta: "Přeskočit intro",
    },
    manifest: {
      label: "Manifest",
      statement: "Nejde jen o to vypadat lépe.",
      statementMuted: "Chci, aby ti trénink pomohl zesílit, zlepšit kondici a naučit se svoje tělo lépe používat.",
      pillars: [
        { title: "Síla", description: "Buduj svaly a postupně zvládni větší zátěž." },
        { title: "Kondice", description: "Měj víc energie a zvládni větší fyzickou zátěž." },
        { title: "Pohyb", description: "Nauč se cvičit technicky, jistě a s kontrolou." },
      ],
    },
    services: {
      label: "Trénink",
      headline: "Trénink podle toho,",
      headlineContinuation: "čeho chceš",
      headlineMuted: "dosáhnout.",
      sectionCta: "Ozvi se",
      items: [
        {
          title: "Získej sílu a svaly",
          text: "Vybuduj silnější tělo, nauč se správnou techniku a postupně nabírej svaly bez zbytečného chaosu.",
          category: "Síla · Svaly · Technika",
          imageAlt: "Atlet při mrtvém tahu",
        },
        {
          title: "Zhubni a dostaň se do formy",
          text: "Sniž tuk, zlepši kondici a nastav trénink tak, aby byl dlouhodobě udržitelný a zapadl do běžného života.",
          category: "Redukce tuku · Forma · Návyky",
          imageAlt: "Postupná změna tělesné kompozice",
        },
        {
          title: "Zlepši kondici a výkon",
          text: "Získej lepší fyzičku, větší pracovní kapacitu a tělo, které zvládne víc než jen posilovnu.",
          category: "Kondice · Vytrvalost · Výkon",
          imageAlt: "Atlet při dynamickém výkonu",
        },
      ],
    },
    process: {
      label: "Proces",
      headline: "Jednoduchý proces.",
      headlineMuted: "Jasný cíl.",
      cta: "Chci konzultaci zdarma",
      steps: [
        { title: "Konzultace zdarma", text: "Nezávazné setkání. Cíl, historie a pohybový screening." },
        { title: "Plán", text: "Struktura tréninku na míru tvému času a zatížení." },
        { title: "Trénink", text: "Vedení, korekce techniky a průběžné ladění." },
        { title: "Progres", text: "Měření, revize čísel a další cyklus." },
      ],
    },
    about: {
      label: "O mně",
      headlineFirst: "Trenér.",
      headlineMuted: "Sportovec.",
      headline: "Coach.",
      portraitLabel: "Matej Červenka",
      portraitAlt: "Osobní trenér Matej Červenka",
      description: "Jsem certifikovaný osobní trenér a ve vlastním tréninku propojuji silový trénink, kalisteniku a zkušenosti z thajského boxu. Klientům ale nestavím trénink podle sebe — stavím ho podle jejich cíle, úrovně a možností.",
      stats: [
        { value: "Certifikovaný", label: "Osobní trenér" },
        { value: "10+", label: "Roky vlastního tréninku" },
        { value: "1:1", label: "Individuální vedení" },
      ],
    },
    diagnostic: {
      label: "Přístup",
      headline: "Nehádám.",
      headlineMuted: "Analyzuji.",
      summary: "Každé tělo je jiné. Než začneme přidávat zátěž, zjistíme, jak se hýbeš, co drží a co chybí. Trénink potom není odhad, ale rozhodnutí.",
      detailsLabel: "Součásti individuálního přístupu",
      details: [
        { title: "Pohybová analýza", description: "Screening kloubní mobility, stability a základních pohybových vzorů." },
        { title: "Technika cviků", description: "Rozbor provedení, korekce a nastavení bezpečné progrese." },
        { title: "Slabá místa", description: "Identifikace limitujících článků, které brzdí dalšímu výkonu." },
        { title: "Individuální plán", description: "Programování podle tvé historie, času a cíle — ne podle šablony." },
      ],
    },
    references: {
      label: "Reference",
      headlineMuted: "Skutečná zpětná vazba.",
      headline: "Bez přikrášlení.",
      summary: "Reference doplňuji postupně. Zveřejním tu pouze skutečné zprávy klientů s jejich souhlasem.",
      cards: [
        { label: "Noví klienti", message: "Aktuálně přijímám nové klienty na osobní tréninky ve Zlíně." },
        { label: "Transparentně", message: "První ověřené zprávy klientů sem doplním postupně a vždy s jejich souhlasem." },
        { label: "Bez zkratek", message: "Žádné vymyšlené proměny. Jen poctivá práce, pravidelnost a výsledky v reálném kontextu." },
      ],
      coach: "Matej · trenér",
      pending: "Reference se připravují",
    },
    contact: {
      label: "Kontakt",
      headlineMuted: "Vybuduj tělo,",
      headline: "které zvládne víc.",
      summary: "Napiš mi svůj cíl a zjistíme, jestli je osobní trénink v Zlíně pro tebe správná cesta.",
      availability: "Přijímám nové klienty",
      location: "Zlín · osobní trénink",
      formLabel: "Kontaktní formulář",
      fields: {
        name: "Jméno",
        contact: "E-mail, telefon nebo Instagram",
        goal: "Tvůj cíl",
        message: "Zpráva",
      },
      goalPlaceholder: "Vyber svůj cíl",
      otherGoal: "Nejsem si jistý / jiný cíl",
      submit: "Odeslat zprávu",
      sending: "Odesílám...",
      success: "Děkuju. Zpráva byla odeslána.",
      error: "Zprávu se nepodařilo odeslat. Zkus to prosím znovu.",
      formNote: "Ozvu se ti co nejdříve s návrhem dalšího kroku.",
    },
    footer: {
      homeLabel: "Matej Červenka — zpět nahoru",
      tagline: "Osobní silový a kondiční trénink v Zlíně",
      navigationLabel: "Navigace v patičce",
      instagramPending: "Instagram — odkaz bude doplněn",
    },
  },
  sk: {
    navigation: [
      { label: "Tréning", href: "#coaching" },
      { label: "Proces", href: "#process" },
      { label: "O mne", href: "#about" },
      { label: "Referencie", href: "#results" },
      { label: "Kontakt", href: "#contact" },
    ],
    header: {
      homeLabel: "Matej Červenka — domov",
      navigationLabel: "Hlavná navigácia",
      languageLabel: "Jazyk obsahu",
    },
    hero: {
      ariaLabel: "Tréningový manifest",
      progressLabel: "Postup kapitol",
      chapters: [
        { discipline: "Sila", headline: ["Buduj", "silu."] },
        { discipline: "Vytrvalosť", headline: ["Buduj", "vytrvalosť."] },
        { discipline: "Výkon", headline: ["Buduj", "výkon."] },
      ],
      finalLabel: "OSOBNÝ TRÉNER · ZLÍN",
      finalLineOne: "Vybuduj telo,",
      finalLineTwo: "ktoré zvládne",
      finalLineThree: "viac.",
      finalLead: "Získaj silu, lepšiu postavu a kondíciu vďaka tréningu nastavenému podľa tvojho cieľa a aktuálnej úrovne.",
      finalServices: "1:1 · DUO / MALÁ SKUPINA · KONDIČNÝ BOX",
      finalCta: "Chcem začať",
      skipCta: "Preskočiť intro",
    },
    manifest: {
      label: "Manifest",
      statement: "Nejde len o to vyzerať lepšie.",
      statementMuted: "Chcem, aby ti tréning pomohol zosilnieť, zlepšiť kondíciu a naučiť sa svoje telo lepšie používať.",
      pillars: [
        { title: "Sila", description: "Buduj svaly a postupne zvládni väčšiu záťaž." },
        { title: "Kondícia", description: "Maj viac energie a zvládni väčšiu fyzickú záťaž." },
        { title: "Pohyb", description: "Nauč sa cvičiť technicky, isto a s kontrolou." },
      ],
    },
    services: {
      label: "Tréning",
      headline: "Tréning podľa toho,",
      headlineContinuation: "čo chceš",
      headlineMuted: "dosiahnuť.",
      sectionCta: "Ozvi sa",
      items: [
        {
          title: "Získaj silu a svaly",
          text: "Vybuduj silnejšie telo, nauč sa správnu techniku a postupne naberaj svaly bez zbytočného chaosu.",
          category: "Sila · Svaly · Technika",
          imageAlt: "Atlét pri mŕtvom ťahu",
        },
        {
          title: "Schudni a dostaň sa do formy",
          text: "Zníž množstvo tuku, zlepši kondíciu a nastav tréning tak, aby bol dlhodobo udržateľný a zapadol do bežného života.",
          category: "Redukcia tuku · Forma · Návyky",
          imageAlt: "Postupná zmena telesnej kompozície",
        },
        {
          title: "Zlepši kondíciu a výkon",
          text: "Získaj lepšiu kondíciu, väčšiu pracovnú kapacitu a telo, ktoré zvládne viac než len posilňovňu.",
          category: "Kondícia · Vytrvalosť · Výkon",
          imageAlt: "Atlét pri dynamickom výkone",
        },
      ],
    },
    process: {
      label: "Proces",
      headline: "Jednoduchý proces.",
      headlineMuted: "Jasný cieľ.",
      cta: "Chcem konzultáciu zadarmo",
      steps: [
        { title: "Konzultácia zadarmo", text: "Nezáväzné stretnutie. Cieľ, história a pohybový screening." },
        { title: "Plán", text: "Štruktúra tréningu na mieru tvojmu času a záťaži." },
        { title: "Tréning", text: "Vedenie, korekcia techniky a priebežné ladenie." },
        { title: "Progres", text: "Meranie, revízia čísel a ďalší cyklus." },
      ],
    },
    about: {
      label: "O mne",
      headlineFirst: "Tréner.",
      headlineMuted: "Športovec.",
      headline: "Coach.",
      portraitLabel: "Matej Červenka",
      portraitAlt: "Osobný tréner Matej Červenka",
      description: "Som certifikovaný osobný tréner a vo vlastnom tréningu prepájam silový tréning, kalisteniku a skúsenosti z thajského boxu. Klientom však nestaviam tréning podľa seba — staviam ho podľa ich cieľa, úrovne a možností.",
      stats: [
        { value: "Certifikovaný", label: "Osobný tréner" },
        { value: "10+", label: "Rokov vlastného tréningu" },
        { value: "1:1", label: "Individuálne vedenie" },
      ],
    },
    diagnostic: {
      label: "Prístup",
      headline: "Nehádam.",
      headlineMuted: "Analyzujem.",
      summary: "Každé telo je iné. Skôr než začneme pridávať záťaž, zistíme, ako sa hýbeš, čo drží a čo chýba. Tréning potom nie je odhad, ale rozhodnutie.",
      detailsLabel: "Súčasti individuálneho prístupu",
      details: [
        { title: "Pohybová analýza", description: "Screening kĺbovej hybnosti, stability a základných vzorov pohybu." },
        { title: "Technika cvikov", description: "Rozbor prevedenia, korekcia a nastavenie bezpečnej progresie." },
        { title: "Slabé miesta", description: "Identifikácia limitujúcich článkov, ktoré brzdia zvyšok výkonu." },
        { title: "Individuálny plán", description: "Programovanie podľa tvojej histórie, času a cieľa — nie podľa šablóny." },
      ],
    },
    references: {
      label: "Referencie",
      headlineMuted: "Skutočná spätná väzba.",
      headline: "Bez prikrášlenia.",
      summary: "Referencie dopĺňam postupne. Zverejním tu iba skutočné správy klientov s ich súhlasom.",
      cards: [
        { label: "Noví klienti", message: "Aktuálne prijímam nových klientov na osobné tréningy v Zlíne." },
        { label: "Transparentne", message: "Prvé overené správy klientov sem doplním postupne a vždy s ich súhlasom." },
        { label: "Bez skratiek", message: "Žiadne vymyslené premeny. Iba poctivá práca, pravidelnosť a výsledky v reálnom kontexte." },
      ],
      coach: "Matej · tréner",
      pending: "Referencie sa pripravujú",
    },
    contact: {
      label: "Kontakt",
      headlineMuted: "Vybuduj telo,",
      headline: "ktoré zvládne viac.",
      summary: "Napíš mi svoj cieľ a zistíme, či je osobný tréning v Zlíne pre teba správna cesta.",
      availability: "Prijímam nových klientov",
      location: "Zlín · osobný tréning",
      formLabel: "Kontaktný formulár",
      fields: {
        name: "Meno",
        contact: "E-mail, telefón alebo Instagram",
        goal: "Tvoj cieľ",
        message: "Správa",
      },
      goalPlaceholder: "Vyber svoj cieľ",
      otherGoal: "Nie som si istý / iný cieľ",
      submit: "Odoslať správu",
      sending: "Odosielam...",
      success: "Ďakujem. Správa bola odoslaná.",
      error: "Správu sa nepodarilo odoslať. Skús to, prosím, znova.",
      formNote: "Ozvem sa ti čo najskôr s návrhom ďalšieho kroku.",
    },
    footer: {
      homeLabel: "Matej Červenka — späť nahor",
      tagline: "Osobný silový a kondičný tréning v Zlíne",
      navigationLabel: "Navigácia v pätičke",
      instagramPending: "Instagram — odkaz bude doplnený",
    },
  },
} as const;

export type Locale = keyof typeof siteContent;
export type ContactGoal = "" | "strength" | "shape" | "performance" | "other";
