export const siteContent = {
  cs: {
    navigation: [
      { label: "Trénink", href: "#coaching" },
      { label: "O mně", href: "#about" },
      { label: "Proces", href: "#process" },
      { label: "Reference", href: "#results" },
      { label: "Kontakt", href: "#contact" },
    ],
    header: {
      homeLabel: "Matej Červenka — domů",
      navigationLabel: "Hlavní navigace",
      languageLabel: "Jazyk obsahu",
      menuLabel: "Mobilní navigace",
      menuOpen: "Otevřít menu",
      menuClose: "Zavřít menu",
    },
    hero: {
      ariaLabel: "Tréninkový manifest",
      progressLabel: "Postup kapitol",
      chapters: [
        { discipline: "Síla", headline: ["Buduj", "sílu."] },
        { discipline: "Vytrvalost", headline: ["Buduj", "vytrvalost."] },
        { discipline: "Výkon", headline: ["Buduj", "výkon."] },
      ],
      finalLabel: "OSOBNÍ TRENÉR · ZLÍN",
      finalLineOne: "Vybuduj tělo,",
      finalLineTwo: "které zvládne",
      finalLineThree: "víc.",
      finalLead: "Ať začínáš od nuly, chceš zhubnout, zesílit nebo se jednoduše cítit lépe ve svém těle. Trénink nastavíme tak, aby ti seděl, bavil tě a přinášel výsledky.",
      finalDescription: "",
      finalServices: "1:1 · DUO",
      finalCta: "Domluvit úvodní konzultaci",
      skipCta: "Přeskočit",
    },
    manifest: {
      label: "Manifest",
      statement: "Nejde jen o to,",
      statementMuted: "jak vypadáš.",
      description: "Chci, aby tvoje tělo bylo silnější, výkonnější a fungovalo lépe i mimo posilovnu.",
    },
    services: {
      label: "Trénink",
      headline: "Trénink podle toho,",
      headlineContinuation: "čeho chceš",
      headlineMuted: "dosáhnout.",
      sectionCta: "Domluvit úvodní konzultaci",
      collaboration: {
        label: "Jak můžeme spolupracovat",
        formats: [
          {
            title: "Osobní trénink 1:1",
            text: "Individuální vedení, technika a trénink nastavený podle tvého cíle, zkušeností a možností.",
          },
          {
            title: "Duo trénink",
            text: "Trénink ve dvojici pro ty, kteří chtějí cvičit společně a přitom mít osobní vedení.",
          },
        ],
        addonTitle: "Vlastní tréninkový plán",
        addonLabel: "Doplněk k osobním tréninkům",
        addonText: "Chceš mezi společnými tréninky cvičit i sám? Připravím ti plán navazující na naše osobní tréninky, podle kterého můžeš pokračovat samostatně.",
      },
      items: [
        {
          title: "Získej sílu a svaly",
          text: "Vybuduj silnější tělo, nauč se správnou techniku a nabírej svaly s jasným plánem.",
          category: "Síla · Svaly · Technika",
          imageAlt: "Atlet při mrtvém tahu",
        },
        {
          title: "Zhubni a dostaň se do formy",
          text: "Sniž tuk, zlepši kondici a nastav trénink tak, aby zapadl do běžného života.",
          category: "Redukce tuku · Forma · Návyky",
          imageAlt: "Postupná změna tělesné kompozice",
        },
        {
          title: "Zlepši kondici a výkon",
          text: "Získej lepší fyzičku a tělo, které zvládne víc než jen posilovnu.",
          category: "Kondice · Vytrvalost · Výkon",
          imageAlt: "Atlet při dynamickém výkonu",
        },
      ],
    },
    process: {
      label: "Proces",
      headline: "Nemusíš vědět,",
      headlineMuted: "kde začít.",
      summary: "Společně nastavíme jasný postup od prvního setkání po další progres.",
      cta: "Domluvit úvodní konzultaci",
      steps: [
        { title: "Poznáme tvůj cíl", text: "Co chceš změnit, kolik máš času a odkud začínáš." },
        { title: "Zjistíme výchozí bod", text: "Podíváme se na pohyb, techniku a tvoje možnosti." },
        { title: "Nastavíme plán", text: "Trénink podle cíle, úrovně a reálného režimu." },
        { title: "Budujeme progres", text: "Postupně přidáváme náročnost podle výsledků." },
      ],
    },
    about: {
      label: "O mně",
      headlineFirst: "Matej",
      headlineMuted: "Osobní trenér.",
      portraitLabel: "Matej Červenka",
      portraitAlt: "Osobní trenér Matej Červenka",
      paragraphs: [
        "Jsem certifikovaný osobní trenér a sport je součástí mého života více než deset let. Ve vlastním tréninku propojuji silový trénink, kalisteniku a zkušenosti z thajského boxu.",
      ],
      stats: [
        { value: "Certifikovaný", label: "Osobní trenér" },
        { value: "10+ let", label: "Vlastního tréninku" },
        { value: "100 %", label: "Individuální vedení" },
      ],
    },
    diagnostic: {
      label: "Přístup",
      headline: "Žádné náhodné",
      headlineMuted: "cvičení.",
      summary: [
        "Trénink není náhodný. Každý cvik a další krok mají jasný důvod.",
      ],
      conclusion: "",
      detailsLabel: "Součásti individuálního přístupu",
      details: [
        { title: "Technika", description: "Nejdřív se naučíš pohyb správně." },
        { title: "Plán podle tebe", description: "Trénink nastavíme podle tvého cíle, zkušeností a možností." },
        { title: "Progres", description: "Náročnost zvyšujeme postupně podle toho, jak se posouváš." },
      ],
    },
    references: {
      label: "Reference",
      headline: "Co říkají klienti.",
      carouselLabel: "Reference klientů",
      previousLabel: "Předchozí reference",
      nextLabel: "Další reference",
      cards: [
        { name: "Demo 01", goal: "Cíl bude doplněn", quote: "[TEXT REFERENCE DOPLNÍM]", service: "Typ spolupráce bude doplněn" },
        { name: "Demo 02", goal: "Cíl bude doplněn", quote: "[TEXT REFERENCE DOPLNÍM]", service: "Typ spolupráce bude doplněn" },
        { name: "Demo 03", goal: "Cíl bude doplněn", quote: "[TEXT REFERENCE DOPLNÍM]", service: "Typ spolupráce bude doplněn" },
        { name: "Demo 04", goal: "Cíl bude doplněn", quote: "[TEXT REFERENCE DOPLNÍM]", service: "Typ spolupráce bude doplněn" },
      ],
    },
    faq: {
      ariaLabel: "Časté otázky",
      label: "Otázky",
      headline: "Možná se",
      headlineMuted: "chceš nejdřív zeptat.",
      items: [
        {
          question: "Je trénink vhodný i pro úplného začátečníka?",
          answer: "Ano. Nemusíš znát cviky ani vědět, jak fungují stroje. Všechno projdeme postupně od základů.",
        },
        {
          question: "Kolikrát týdně je potřeba trénovat?",
          answer: "Frekvenci nastavíme podle tvého cíle a času. Důležitý je režim, který dokážeš dlouhodobě dodržovat.",
        },
        {
          question: "Pomůžeš mi i s redukcí tuku a stravou?",
          answer: "Ano. Trénink doplníme praktickými doporučeními ke stravě, která podporují tvůj cíl bez zbytečných extrémů.",
        },
        {
          question: "Jak probíhá první konzultace?",
          answer: "Krátce probereme tvůj cíl, zkušenosti a možnosti. Konzultace je zdarma a bez závazku.",
        },
      ],
    },
    contact: {
      label: "Kontakt",
      headlineMuted: "Vybuduj tělo,",
      headline: "které zvládne víc.",
      summary: [
        "Úvodní konzultace je zdarma a bez závazku.",
      ],
      offer: "",
      availability: "Přijímám nové klienty",
      location: "Zlín · osobní trénink",
      formLabel: "Kontaktní formulář",
      fields: {
        name: "Jméno",
        contact: "E-mail, telefon nebo Instagram",
        message: "Tvoje zpráva",
      },
      submit: "Domluvit úvodní konzultaci",
      sending: "Odesílám...",
      success: "Děkuju. Zpráva byla odeslána.",
      error: "Zprávu se nepodařilo odeslat. Zkus to prosím znovu.",
      formNote: "Ozvu se ti co nejdříve s návrhem dalšího kroku.",
    },
    footer: {
      homeLabel: "Matej Červenka — zpět nahoru",
      tagline: "Osobní silový a kondiční trénink v Zlíně",
      navigationLabel: "Navigace v patičce",
      instagramPending: "Instagram — odkaz bude doplněn",
    },
  },
  sk: {
    navigation: [
      { label: "Tréning", href: "#coaching" },
      { label: "O mne", href: "#about" },
      { label: "Proces", href: "#process" },
      { label: "Referencie", href: "#results" },
      { label: "Kontakt", href: "#contact" },
    ],
    header: {
      homeLabel: "Matej Červenka — domov",
      navigationLabel: "Hlavná navigácia",
      languageLabel: "Jazyk obsahu",
      menuLabel: "Mobilná navigácia",
      menuOpen: "Otvoriť menu",
      menuClose: "Zavrieť menu",
    },
    hero: {
      ariaLabel: "Tréningový manifest",
      progressLabel: "Postup kapitol",
      chapters: [
        { discipline: "Sila", headline: ["Buduj", "silu."] },
        { discipline: "Vytrvalosť", headline: ["Buduj", "vytrvalosť."] },
        { discipline: "Výkon", headline: ["Buduj", "výkon."] },
      ],
      finalLabel: "OSOBNÝ TRÉNER · ZLÍN",
      finalLineOne: "Vybuduj telo,",
      finalLineTwo: "ktoré zvládne",
      finalLineThree: "viac.",
      finalLead: "Či už začínaš od nuly, chceš schudnúť, zosilnieť alebo sa jednoducho cítiť lepšie vo svojom tele. Tréning nastavíme tak, aby ti vyhovoval, bavil ťa a prinášal výsledky.",
      finalDescription: "",
      finalServices: "1:1 · DUO",
      finalCta: "Dohodnúť úvodnú konzultáciu",
      skipCta: "Preskočiť",
    },
    manifest: {
      label: "Manifest",
      statement: "Nejde len o to,",
      statementMuted: "ako vyzeráš.",
      description: "Chcem, aby tvoje telo bolo silnejšie, výkonnejšie a fungovalo lepšie aj mimo posilňovne.",
    },
    services: {
      label: "Tréning",
      headline: "Tréning podľa toho,",
      headlineContinuation: "čo chceš",
      headlineMuted: "dosiahnuť.",
      sectionCta: "Dohodnúť úvodnú konzultáciu",
      collaboration: {
        label: "Ako môžeme spolupracovať",
        formats: [
          {
            title: "Osobný tréning 1:1",
            text: "Individuálne vedenie, technika a tréning nastavený podľa tvojho cieľa, skúseností a možností.",
          },
          {
            title: "Duo tréning",
            text: "Tréning vo dvojici pre tých, ktorí chcú cvičiť spoločne a pritom mať osobné vedenie.",
          },
        ],
        addonTitle: "Vlastný tréningový plán",
        addonLabel: "Doplnok k osobným tréningom",
        addonText: "Chceš medzi spoločnými tréningmi cvičiť aj sám? Pripravím ti plán nadväzujúci na naše osobné tréningy, podľa ktorého môžeš pokračovať samostatne.",
      },
      items: [
        {
          title: "Získaj silu a svaly",
          text: "Vybuduj silnejšie telo, nauč sa správnu techniku a naberaj svaly s jasným plánom.",
          category: "Sila · Svaly · Technika",
          imageAlt: "Atlét pri mŕtvom ťahu",
        },
        {
          title: "Schudni a dostaň sa do formy",
          text: "Zníž množstvo tuku, zlepši kondíciu a nastav tréning tak, aby zapadol do bežného života.",
          category: "Redukcia tuku · Forma · Návyky",
          imageAlt: "Postupná zmena telesnej kompozície",
        },
        {
          title: "Zlepši kondíciu a výkon",
          text: "Získaj lepšiu kondíciu a telo, ktoré zvládne viac než len posilňovňu.",
          category: "Kondícia · Vytrvalosť · Výkon",
          imageAlt: "Atlét pri dynamickom výkone",
        },
      ],
    },
    process: {
      label: "Proces",
      headline: "Nemusíš vedieť,",
      headlineMuted: "kde začať.",
      summary: "Spoločne nastavíme jasný postup od prvého stretnutia po ďalší progres.",
      cta: "Dohodnúť úvodnú konzultáciu",
      steps: [
        { title: "Spoznáme tvoj cieľ", text: "Čo chceš zmeniť, koľko máš času a odkiaľ začínaš." },
        { title: "Zistíme východiskový bod", text: "Pozrieme sa na pohyb, techniku a tvoje možnosti." },
        { title: "Nastavíme plán", text: "Tréning podľa cieľa, úrovne a reálneho režimu." },
        { title: "Budujeme progres", text: "Postupne pridávame náročnosť podľa výsledkov." },
      ],
    },
    about: {
      label: "O mne",
      headlineFirst: "Matej",
      headlineMuted: "Osobný tréner.",
      portraitLabel: "Matej Červenka",
      portraitAlt: "Osobný tréner Matej Červenka",
      paragraphs: [
        "Som certifikovaný osobný tréner a šport je súčasťou môjho života viac než desať rokov. Vo vlastnom tréningu prepájam silový tréning, kalisteniku a skúsenosti z thajského boxu.",
      ],
      stats: [
        { value: "Certifikovaný", label: "Osobný tréner" },
        { value: "10+ rokov", label: "Vlastného tréningu" },
        { value: "100 %", label: "Individuálne vedenie" },
      ],
    },
    diagnostic: {
      label: "Prístup",
      headline: "Žiadne náhodné",
      headlineMuted: "cvičenie.",
      summary: [
        "Tréning nie je náhodný. Každý cvik a ďalší krok majú jasný dôvod.",
      ],
      conclusion: "",
      detailsLabel: "Súčasti individuálneho prístupu",
      details: [
        { title: "Technika", description: "Najskôr sa naučíš pohyb správne." },
        { title: "Plán podľa teba", description: "Tréning nastavíme podľa tvojho cieľa, skúseností a možností." },
        { title: "Progres", description: "Náročnosť zvyšujeme postupne podľa toho, ako sa posúvaš." },
      ],
    },
    references: {
      label: "Referencie",
      headline: "Čo hovoria klienti.",
      carouselLabel: "Referencie klientov",
      previousLabel: "Predchádzajúca referencia",
      nextLabel: "Ďalšia referencia",
      cards: [
        { name: "Demo 01", goal: "Cieľ bude doplnený", quote: "[TEXT REFERENCIE DOPLNÍM]", service: "Typ spolupráce bude doplnený" },
        { name: "Demo 02", goal: "Cieľ bude doplnený", quote: "[TEXT REFERENCIE DOPLNÍM]", service: "Typ spolupráce bude doplnený" },
        { name: "Demo 03", goal: "Cieľ bude doplnený", quote: "[TEXT REFERENCIE DOPLNÍM]", service: "Typ spolupráce bude doplnený" },
        { name: "Demo 04", goal: "Cieľ bude doplnený", quote: "[TEXT REFERENCIE DOPLNÍM]", service: "Typ spolupráce bude doplnený" },
      ],
    },
    faq: {
      ariaLabel: "Časté otázky",
      label: "Otázky",
      headline: "Možno sa",
      headlineMuted: "chceš najskôr opýtať.",
      items: [
        {
          question: "Je tréning vhodný aj pre úplného začiatočníka?",
          answer: "Áno. Nemusíš poznať cviky ani vedieť, ako fungujú stroje. Všetko prejdeme postupne od základov.",
        },
        {
          question: "Koľkokrát týždenne je potrebné trénovať?",
          answer: "Frekvenciu nastavíme podľa tvojho cieľa a času. Dôležitý je režim, ktorý dokážeš dlhodobo dodržiavať.",
        },
        {
          question: "Pomôžeš mi aj s redukciou tuku a stravou?",
          answer: "Áno. Tréning doplníme praktickými odporúčaniami k strave, ktoré podporujú tvoj cieľ bez zbytočných extrémov.",
        },
        {
          question: "Ako prebieha prvá konzultácia?",
          answer: "Krátko preberieme tvoj cieľ, skúsenosti a možnosti. Konzultácia je zadarmo a bez záväzku.",
        },
      ],
    },
    contact: {
      label: "Kontakt",
      headlineMuted: "Vybuduj telo,",
      headline: "ktoré zvládne viac.",
      summary: [
        "Úvodná konzultácia je zadarmo a bez záväzku.",
      ],
      offer: "",
      availability: "Prijímam nových klientov",
      location: "Zlín · osobný tréning",
      formLabel: "Kontaktný formulár",
      fields: {
        name: "Meno",
        contact: "E-mail, telefón alebo Instagram",
        message: "Tvoja správa",
      },
      submit: "Dohodnúť úvodnú konzultáciu",
      sending: "Odosielam...",
      success: "Ďakujem. Správa bola odoslaná.",
      error: "Správu sa nepodarilo odoslať. Skús to, prosím, znova.",
      formNote: "Ozvem sa ti čo najskôr s návrhom ďalšieho kroku.",
    },
    footer: {
      homeLabel: "Matej Červenka — späť nahor",
      tagline: "Osobný silový a kondičný tréning v Zlíne",
      navigationLabel: "Navigácia v pätičke",
      instagramPending: "Instagram — odkaz bude doplnený",
    },
  },
} as const;

export type Locale = keyof typeof siteContent;
